set nocompatible


" import windows
if filereadable(expand("~/.vim/vendor/gvim_windows/gvim_windows_default.vim"))
    source ~/.vim/vendor/gvim_windows/gvim_windows_default.vim
endif

if filereadable(expand("~/.vim/vendor/gvim_windows/mswin.vim"))
    source ~/.vim/vendor/gvim_windows/mswin.vim
endif

"Editor setting
"-------------------
syntax enable
syntax on
set number
set expandtab
set tabstop=4
set shiftwidth=4
set smarttab
set autoindent
set incsearch
set hlsearch
set ignorecase


"==============================================
" Vundle
"==============================================
"
" 1)Installation requires Git and triggers git clone
" 2)Curl is required for search.
" 3)Set up Vundle: 
"       WIN> **NO NEED any more**
"       LINUX> $ git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/vendor/vundle.vim
" 4)Configure Plugins
"
filetype off                   " required!

"set rtp+=~/.vim/vendor/snipmate.snippets/
set rtp+=~/.vim/vendor/vundle.vim/

"set rtp+=d:\00_MJ_CODE\01_github_sandbox\py_proj\setup_machine\01_vim_setup\vundle_runtime_new\Vundle.vim
"call vundle#begin("d:\\00_MJ_CODE\\01_github_sandbox\\py_proj\\setup_machine\\01_vim_setup\\vundle_runtime_new")
call vundle#begin()

" let Vundle manage Vundle
" required! 
"Plugin 'VundleVim/vundle.vim'

" My Bundles here:
" ----------------

"Plugin 'taglist.vim'
Plugin 'a.vim'
Plugin 'molokai'
Plugin 'The-NERD-tree'
Plugin 'snipMate'
"Bundle 'minibufexplorerpp'
"Bundle 'AutoComplPop'
Plugin 'OmniCppComplete'
Plugin 'L9'
Plugin 'FuzzyFinder'
"Bundle 'Syntastic'
"Bundle 'VimPdb'
Plugin 'Tagbar'

"Also add PEP8 checking with this nifty little plugin:
"Plugin 'nvie/vim-flake8'
"let python_highlight_all=1


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

"---------------------
"      DOCS
"--------------------
"
" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
"
" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
"
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
"
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
"
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
"
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
"Plugin 'ascenator/L9', {'name': 'newL9'}
"
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

