#!/bin/bash

[ -f /usr/share/bash-completion/completions/git ] && source /usr/share/bash-completion/completions/git  # to complete git

alias .G='git --git-dir=$HOME/foxconfig.git --work-tree=$HOME'
complete -o default -o nospace -F _git .G   # allow git-completion to work with alias aswell

alias G='git'
complete -o default -o nospace -F _git G    # allow git-completion to work with alias aswell


if [ "$(uname)" == "Darwin" ]; then

    alias ll='ls -l -G -a'

elif [ "$(uname -s)" == "Linux" ]; then

    alias ls='ls -G --color=auto'
    alias l='ls -l -G --color=auto'
    alias l.='ls -A -G --color=auto'
    alias ll='ls -l -G -A --color=auto'
    alias mv='mv -i'
    alias rm='rm -i'
    alias m='make'

    alias port='sudo netstat -tunlp'
    alias psgrep='ps ax | grep'
fi


# NGINX
alias ng_reload="echo 'reloading nginx...'; sudo /usr/local/nginx/sbin/nginx -s reload;  echo 'reloaded.'; "
alias ng_conf="cd /usr/local/nginx/conf"
alias ng_log="cd /data/wwwlogs"

# TMUX
alias tmj="tmux attach -t mj"   #attach mj session
alias tmjn="tmux new -s mj"     #new session with name mj

alias st_pull=".G subtree pull --squash -P .vim vimrc master"
alias st_push=".G subtree push -P .vim vimrc master"
